name = "item-manage"
compatibility_date = "2025-12-31"
main = "dist/_worker.js"
assets = { directory = "dist", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "item-manage-db"
database_id = "57f7d311-4762-4eab-ba5d-cd0251d5b764"
migrations_dir = "migrations"
